version: "2"
services:
  prod_backend:
    container_name: prod_backend
    image: scribble/prod:v0.1
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        WORKING_DIR: app_prod
        PORT: 8000
    volumes:
      - .:/app_prod
    expose:
      - "8000"
    networks:
      - redis_network
      - nginx_network
  staging_backend:
    container_name: staging_backend
    image: scribble/staging:v0.1
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        WORKING_DIR: app_staging
        PORT: 8001
    volumes:
    - .:/app_staging
    expose:
      - "8001"
    networks:
      - redis_network
      - nginx_network
  nginx:
    image: nginx:v2
    container_name: nginx
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    volumes:
      - .:/app_prod
      - .:/app_staging
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    ports:
      - "8084:80"
      - "443:443"
    depends_on:
      - prod_backend
    networks:
      - nginx_network
  redis:
    image: "redis:3.2"
    restart: always
    container_name: redis
    hostname: redis
    command: --port 6379
    networks:
      - redis_network
    expose:
      - "6379"
    ports:
      - "6379:6379"

networks:
  redis_network:
    driver: bridge
  nginx_network:
    driver: bridge

