# Generated by Django 4.0.4 on 2022-06-01 10:16

import core.fields
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isbn', core.fields.ISBNField(max_length=28, unique=True, validators=[core.validators.ISBNValidator])),
                ('title', models.CharField(max_length=150, verbose_name='제목')),
                ('author', models.CharField(max_length=150, verbose_name='작가')),
                ('publisher', models.CharField(max_length=150, verbose_name='출판사')),
                ('category', models.JSONField(default=dict)),
                ('thumbnail', models.URLField(blank=True, verbose_name='도서 썸네일')),
            ],
            options={
                'verbose_name': '도서',
                'verbose_name_plural': '도서',
                'db_table': 'book',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hit', models.PositiveSmallIntegerField(default=0, verbose_name='조회수')),
            ],
            options={
                'verbose_name': '필사 노트',
                'verbose_name_plural': '필사 노트',
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='NoteLikesRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '노트_좋아요',
                'verbose_name_plural': '노트_좋아요',
                'db_table': 'note_likes_relation',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_index', models.PositiveSmallIntegerField(default=0, verbose_name='노트 인덱스')),
                ('transcript', models.URLField(verbose_name='필사 이미지')),
                ('phrase', models.TextField(blank=True, null=True, verbose_name='필사 구절')),
                ('hit', models.PositiveSmallIntegerField(default=0, verbose_name='조회수')),
            ],
            options={
                'verbose_name': '필사 페이지',
                'verbose_name_plural': '필사 페이지',
                'db_table': 'page',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depth', models.PositiveSmallIntegerField(default=0, verbose_name='댓글 depth')),
                ('parent', models.PositiveSmallIntegerField(default=0, verbose_name='부모 댓글 idx')),
                ('content', models.TextField(verbose_name='내용')),
            ],
            options={
                'verbose_name': '페이지 댓글',
                'verbose_name_plural': '페이지 댓글',
                'db_table': 'page_comment',
            },
        ),
        migrations.CreateModel(
            name='PageLikesRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '페이지_좋아요',
                'verbose_name_plural': '페이지_좋아요',
                'db_table': 'page_likes_relation',
                'ordering': ['created_at'],
            },
        ),
    ]
