# Generated by Django 4.0.4 on 2022-06-01 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelikesrelation',
            name='like_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_likes_relation', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='pagelikesrelation',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_likes_relation', to='contents.page', verbose_name='페이지'),
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='comment_user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='page_comment', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='page',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='page_comment', to='contents.page', verbose_name='페이지'),
        ),
        migrations.AddField(
            model_name='page',
            name='note',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='page', to='contents.note', verbose_name='노트'),
        ),
        migrations.AddField(
            model_name='notelikesrelation',
            name='like_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_likes_relation', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='notelikesrelation',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_likes_relation', to='contents.note', verbose_name='노트'),
        ),
        migrations.AddField(
            model_name='note',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='note', to='contents.bookobject', verbose_name='도서'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='note', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
