# Generated by Django 4.0.4 on 2022-07-16 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='book_page',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='책페이지'),
        ),
    ]
