# Generated by Django 4.1.4 on 2022-12-27 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_auth_id_user_social_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLoginLog',
        ),
    ]
