name: Auto Release

on: [pull_request]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ contains(github.base_ref, 'main') || contains(github.ref, 'main') }}
    steps:
      - name: Sparse-checkout
        uses: lablup/sparse-checkout@v1
        with:
          patterns: |
            scripts

      - name: Extract version
        id: extract-version
        run: |
          version=$(echo '${{ github.event.pull_request.title }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
          echo "::set-output name=version::$version"

      - name: Auto Generate Changelog
        id: changelog
        if: ${{ steps.extract-version.outputs.version }}
        run: |
          python3 ./scripts/generate_changelog.py --version "${{ steps.extract-version.outputs.version }}"

      - name: Get Changed Files
        id: changed-files
        if: ${{ steps.extract-version.outputs.version }}
        uses: tj-actions/changed-files@v31
        files: |
          **

      - name: Auto Commit Updated Changelog
        id: auto-commit-push
        if: ${{ (steps.changed-files.outputs.any_changed) && (steps.extract-version.outputs.version) }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "update: CHANGELOG.md"
          file_pattern: "CHANGELOG.md"

      - name: Create Release with Tag
        if: ${{ steps.extract-version.outputs.version }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.extract-version.outputs.version }}
          name: ${{ steps.extract-version.outputs.version }}
          bodyFile: "./CHANGELOG_RELEASE.md"
