name: Auto Release

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, closed]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ contains(github.base_ref, 'main') || contains(github.ref, 'main') }}
    steps:
      - name: Sparse-checkout
        uses: lablup/sparse-checkout@v1
        with:
          patterns: |
            scripts

      - name: Extract version
        id: extract-version
        run: |
          version=$(echo '${{ github.event.pull_request.title }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
          echo "::set-output name=version::$version"

      - name: Debug Github Ref
        run: |
          echo "head_ref: ${{ github.head_ref }}"
          echo "ref_name: ${{ github.ref_name }}"

      - name: Auto Generate Changelog
        id: changelog
        if: ${{ steps.extract-version.outputs.version }}
        run: |
          python3 ./scripts/generate_changelog.py --version "${{ steps.extract-version.outputs.version }}" --tag "${{ github.head_ref }}"

      - name: Get Changed Files
        id: changed-files
        if: ${{ github.event.action != 'closed' && steps.extract-version.outputs.version }}
        uses: tj-actions/changed-files@v31

      - name: Auto Commit Updated Changelog
        id: auto-commit-push
        if: ${{ github.event.action != 'closed' && steps.changed-files.outputs.any_changed == true && steps.extract-version.outputs.version }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "update: CHANGELOG.md"
          file_pattern: "CHANGELOG.md"

      - name: Create Release with Tag
        if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true && steps.extract-version.outputs.version == true && contains(github.event.pull_request.title, 'release') }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.extract-version.outputs.version }}
          name: ${{ steps.extract-version.outputs.version }}
          bodyFile: "./CHANGELOG_RELEASE.md"
          skipIfReleaseExists: true
