name: build-ci-check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create env file
        working-directory: ./app
        run: |
          touch scribble/.env
          echo "${{ secrets.ENV_VARS }}" >> .env

      - name: Setup python ${{matrix.python-version}}
        uses: action/setup-python@v3
        with:
          python-version: ${{matrix.python-version}}

      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker-compose
        run: docker-compose up -d --build
