name: build-ci-check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch scribble/.env
          echo "${{ secrets.ENV_VARS }}" >> .env

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker-compose
        run: |
          docker-compose down && docker-compose up -d --build
