name: build-ci-check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch scribble/.env
          echo "${{ secrets.ENV_VARS }}" >> .env

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install docker setup script
        run: sh setup.sh

      - name: Build docker-compose
        run: |
          sudo kill `sudo lsof -t -i:8084` && docker-compose down && docker-compose up -d --build

      - name: Check docker container running
        run: |
          echo $(
            count = $(docker ps --format "{{.Names}} {{.Status}}" | grep "Up" -c)
            if [ $count -ne 3 ]; then
              exit 1
            else
              echo "backend, nginx, redis container running"
            fi
          )
