name: Schedule Deployment

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  checkout:
    runs-on: [ self-hosted, label-go ]
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Set Permissions
        run: sudo chown -R $USER:$USER ${{ github.workspace }}

      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Setup Docker
        run: sh scripts/setup-docker.sh

  deploy:
    runs-on: [ self-hosted, label-go ]
    needs: checkout
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Create env file
        run: |
          : > ${{ secrets.ENV_PATH }}
          touch ${{ secrets.ENV_PATH }}
          {
            echo NAVER_API_CLIENT_ID="\"${{ secrets.NAVER_API_CLIENT_ID }}"\"
            echo NAVER_API_CLIENT_SECRET="\"${{ secrets.NAVER_API_CLIENT_SECRET }}"\"
            echo SECRET_KEY="\"${{ secrets.SECRET_KEY }}"\"
            echo RUN_ENV="\"${{ secrets.RUN_ENV }}"\"
            echo DOMAIN="\"${{ secrets.DOMAIN }}"\"
            echo PROD_ALLOWED_HOSTS='${{ secrets.PROD_ALLOWED_HOSTS }}'
            echo CORS_ORIGIN_WHITELIST='${{ secrets.CORS_ORIGIN_WHITELIST }}'
            echo DB_NAME="\"${{ secrets.DB_NAME }}"\"
            echo DB_USER="\"${{ secrets.DB_USER }}"\"
            echo DB_HOST="\"${{ secrets.DB_HOST }}"\"
            echo DB_PASSWORD="\"${{ secrets.DB_PASSWORD }}"\"
            echo LOG_DIR="\"${{ secrets.LOG_DIR }}"\"
            echo LOG_FILENAME="\"${{ secrets.LOG_FILENAME }}"\"
            echo SENTRY_DSN="\"${{ secrets.SENTRY_DSN }}"\"
          } >> ${{ secrets.ENV_PATH }}

      - name: Build Docker containers
        run: sh scripts/build-docker-compose.sh

      - name: Check container running state
        run: |
          if [ $(docker ps --format "{{.Names}} {{.Status}}" | grep "Up" | wc -l) -ne 3 ]
          then
            echo "Build error while running docker-compose"
            exit 1
          else
            echo "Deploy Complete"
          fi

  test:
    runs-on: [ self-hosted, label-go ]
    needs: [ checkout, deploy ]
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Send cURL to validate server and ssl cerficiate
        run: |
          RESP_CODE=$(curl -LI https://${{ secrets.DOMAIN }}/v1/docs -o /dev/null -w '%{http_code}\n' -s)
          if [ $RESP_CODE -eq 200 ]
          then
            echo "Success $RESP_CODE: SSL certificate verify ok."
          else
            exit 1
          fi

  rollback:
    runs-on: [ self-hosted, label-go ]
    needs: [ checkout, deploy, test ]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Set Action Runner Permissions
        run: sudo chown -R $USER:$USER ${{ github.workspace }}

      - name: Fetch Latest Release
        id: fetch-latest
        uses: thebritican/fetch-latest-release@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Latest Release source code
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.fetch-latest.outputs.tag_name }}

      - name: Build Docker containers
        run: sh scripts/build-docker-compose.sh

      - name: Check container running state
        run: |
          if [ $(docker ps --format "{{.Names}} {{.Status}}" | grep "Up" | wc -l) -ne 3 ]
          then
            echo "Build error while running docker-compose"
            exit 1
          else
            echo "Deploy Complete"
          fi

  tagging:
    runs-on: [ self-hosted, label-go ]
    needs: [ checkout, deploy, test ]
    if: ${{ always() && github.event.pull_request.merged == true && needs.checkout.result == 'success' && needs.deploy.result == 'success' && needs.test.result == 'success' }}
    steps:
      - name: Extract version
        run: |
          version=$(echo '${{ github.event.pull_request.title }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
          if [ -z $version ]; then
            exit 1
          else
            echo "::set-output name=version::$version"
          fi
        id: extract-version

      - name: Auto Generate Changelog
        run: |
          python3 change.py --version "${{ steps.extract-version.outputs.version }}"
        id: changelog

      - name: Create Release with Tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract-version.outputs.version }}
          release_name: ${{ steps.extract-version.outputs.version }}
